<?php
ob_start(); // Prevents accidental output before PDF is sent

require_once 'classes/fpdf/fpdf.php';
require_once 'classes/application.php';

// Get application ID
$appId = isset($_GET['id']) ? intval($_GET['id']) : 0;
$application = null;

// Fetch application if ID is valid
if ($appId > 0) {
    $appObj = new Application();
    if (method_exists($appObj, 'getApplicationById')) {
        $application = $appObj->getApplicationById($appId);
    }
}

// // Stop if data not found
// if (!$application || !is_array($application)) {
//     ob_end_clean(); // Clear output buffer before error
//     die("Certificate data not found.");
// }

// Prepare data
$name = htmlspecialchars($application['businessName']);
$issue_date = date("F j, Y", strtotime($application['issueDate']));
$expiry_date = date("F j, Y", strtotime($application['expiryDate']));
$type_of_business = htmlspecialchars($application['businessType']);
$amount_paid = "K" . number_format(floatval($application['amount']), 2);

// Generate PDF
$pdf = new FPDF('L', 'mm', 'A4');
$pdf->AddPage();

// Background
if (file_exists('certificate-background.jpg')) {
    $pdf->Image('certificate-background.jpg', 0, 0, 297, 210);
}

// Logo (centered)
if (file_exists('logo.png')) {
    $logoWidth = 35;
    $logoX = (297 - $logoWidth) / 2;
    $logoY = 15;
    $pdf->Image('logo.png', $logoX, $logoY, $logoWidth);
}

// Main Title (add more space below logo)
$pdf->SetFont('Arial', 'B', 36);
$pdf->SetTextColor(0, 51, 102);
// Start title further down for more spacing after logo
$pdf->SetXY(0, 60);
$pdf->Cell(297, 20, 'Business Permit Certificate', 0, 1, 'C');

// Subtitle
$pdf->SetFont('Arial', 'I', 18);
$pdf->SetTextColor(60, 60, 60);
$pdf->SetXY(0, 85);
$pdf->Cell(297, 12, 'This certifies that the following business is duly registered:', 0, 1, 'C');

// Business Name
$pdf->SetFont('Arial', 'B', 28);
$pdf->SetTextColor(0, 102, 204);
$pdf->SetXY(0, 105);
$pdf->Cell(297, 16, $name, 0, 1, 'C');

// Details Box (move up slightly)
$pdf->SetDrawColor(180, 180, 180);
$pdf->SetLineWidth(0.5);
$pdf->Rect(40, 120, 217, 65, 'D'); // Y=120 (was 130)

// Details - stacked vertically
$detailY = 130; // Start details higher (was 140)
$lineHeight = 13;

$pdf->SetFont('Arial', '', 16);
$pdf->SetTextColor(40, 40, 40);

$pdf->SetXY(50, $detailY);
$pdf->Cell(60, 10, "Type of Business:", 0, 0, 'L');
$pdf->SetFont('Arial', 'B', 16);
$pdf->Cell(100, 10, $type_of_business, 0, 1, 'L');

$pdf->SetFont('Arial', '', 16);
$pdf->SetXY(50, $detailY + $lineHeight);
$pdf->Cell(60, 10, "Issue Date:", 0, 0, 'L');
$pdf->SetFont('Arial', 'B', 16);
$pdf->Cell(100, 10, $issue_date, 0, 1, 'L');

$pdf->SetFont('Arial', '', 16);
$pdf->SetXY(50, $detailY + 2 * $lineHeight);
$pdf->Cell(60, 10, "Expiry Date:", 0, 0, 'L');
$pdf->SetFont('Arial', 'B', 16);
$pdf->Cell(100, 10, $expiry_date, 0, 1, 'L');

$pdf->SetFont('Arial', '', 16);
$pdf->SetXY(50, $detailY + 3 * $lineHeight);
$pdf->Cell(60, 10, "Amount Paid:", 0, 0, 'L');
$pdf->SetFont('Arial', 'B', 16);
$pdf->Cell(100, 10, $amount_paid, 0, 1, 'L');

// Footer
$pdf->SetFont('Arial', 'I', 12);
$pdf->SetTextColor(120, 120, 120);
$pdf->SetXY(0, 170);
// Output PDF7, 10, 'Generated by Permit Manager | Certificate ID: ' . $appId, 0, 1, 'C');
$filename = "certificate_" . preg_replace("/[^A-Za-z0-9]/", "_", $name) . ".pdf";
ob_end_clean(); // Clear any buffered output
$pdf->Output('I', $filename);preg_replace("/[^A-Za-z0-9]/", "_", $name) . ".pdf";
exit;d_clean(); // Clear any buffered output
?>df->Output('I', $filename);
exit;
?>
