<?php
ob_start();

require_once 'classes/fpdf/fpdf.php';
require_once 'classes/application.php';

// Get application ID 
$appId = intval($_GET['id']);
$appObj = new Application();
$application = $appObj->getApplicationById($appId);

// // Optional: Debug only if something's wrong
// if (!$application) {
//     ob_end_clean();
//     die("Application not found or data missing.");
// }

// Prepare data
$name = htmlspecialchars($application['businessName']);
$issue_date = date("F j, Y", strtotime($application['issueDate']));
$expiry_date = date("F j, Y", strtotime($application['expiryDate']));
$type_of_business = htmlspecialchars($application['businessType']);
$amount_paid = "K" . number_format(floatval($application['amount']), 2);

// Generate PDF
$pdf = new FPDF('L', 'mm', 'A4');
$pdf->AddPage();

// Background
if (file_exists('certificate-background.jpg')) {
    $pdf->Image('certificate-background.jpg', 0, 0, 297, 210);
}

// Logo
if (file_exists('logo.png')) {
    $logoWidth = 35;
    $logoX = (297 - $logoWidth) / 2;
    $logoY = 15;
    $pdf->Image('logo.png', $logoX, $logoY, $logoWidth);
}

// Title
$pdf->SetFont('Arial', 'B', 36);
$pdf->SetTextColor(0, 51, 102);
$pdf->SetXY(0, 60);
$pdf->Cell(297, 20, 'Business Permit Certificate', 0, 1, 'C');

// Subtitle
$pdf->SetFont('Arial', 'I', 18);
$pdf->SetTextColor(60, 60, 60);
$pdf->SetXY(0, 85);
$pdf->Cell(297, 12, 'This certifies that the following business is duly registered:', 0, 1, 'C');

// Business Name
$pdf->SetFont('Arial', 'B', 28);
$pdf->SetTextColor(0, 102, 204);
$pdf->SetXY(0, 105);
$pdf->Cell(297, 16, $name, 0, 1, 'C');

// Box
$pdf->SetDrawColor(180, 180, 180);
$pdf->SetLineWidth(0.5);
$pdf->Rect(40, 120, 217, 65, 'D');

// Info lines
$detailY = 130;
$lineHeight = 13;

$pdf->SetFont('Arial', '', 16);
$pdf->SetTextColor(40, 40, 40);

$pdf->SetXY(50, $detailY);
$pdf->Cell(60, 10, "Type of Business:", 0, 0, 'L');
$pdf->SetFont('Arial', 'B', 16);
$pdf->Cell(100, 10, $type_of_business, 0, 1, 'L');

$pdf->SetFont('Arial', '', 16);
$pdf->SetXY(50, $detailY + $lineHeight);
$pdf->Cell(60, 10, "Issue Date:", 0, 0, 'L');
$pdf->SetFont('Arial', 'B', 16);
$pdf->Cell(100, 10, $issue_date, 0, 1, 'L');

$pdf->SetFont('Arial', '', 16);
$pdf->SetXY(50, $detailY + 2 * $lineHeight);
$pdf->Cell(60, 10, "Expiry Date:", 0, 0, 'L');
$pdf->SetFont('Arial', 'B', 16);
$pdf->Cell(100, 10, $expiry_date, 0, 1, 'L');

$pdf->SetFont('Arial', '', 16);
$pdf->SetXY(50, $detailY + 3 * $lineHeight);
$pdf->Cell(60, 10, "Amount Paid:", 0, 0, 'L');
$pdf->SetFont('Arial', 'B', 16);
$pdf->Cell(100, 10, $amount_paid, 0, 1, 'L');

// Footer (optional)
// $pdf->SetFont('Arial', 'I', 12);
// $pdf->SetTextColor(120, 120, 120);
// $pdf->SetXY(0, 170);
// $pdf->Cell(297, 10, 'Generated by Permit Manager | Certificate ID: ' . $appId, 0, 1, 'C');

// Output
$filename = "certificate_" . preg_replace("/[^A-Za-z0-9]/", "_", $name) . ".pdf";
ob_end_clean();
$pdf->Output('I', $filename);
exit;
?>
